'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import { WfButton as WfButtonElement, defineCustomElement as defineWfButton } from "wireframes/dist/components/wf-button.js";
import { WfCheckbox as WfCheckboxElement, defineCustomElement as defineWfCheckbox } from "wireframes/dist/components/wf-checkbox.js";
import { WfFlex as WfFlexElement, defineCustomElement as defineWfFlex } from "wireframes/dist/components/wf-flex.js";
import { WfGrid as WfGridElement, defineCustomElement as defineWfGrid } from "wireframes/dist/components/wf-grid.js";
import { WfHr as WfHrElement, defineCustomElement as defineWfHr } from "wireframes/dist/components/wf-hr.js";
import { WfImage as WfImageElement, defineCustomElement as defineWfImage } from "wireframes/dist/components/wf-image.js";
import { WfInput as WfInputElement, defineCustomElement as defineWfInput } from "wireframes/dist/components/wf-input.js";
import { WfLink as WfLinkElement, defineCustomElement as defineWfLink } from "wireframes/dist/components/wf-link.js";
import { WfLorem as WfLoremElement, defineCustomElement as defineWfLorem } from "wireframes/dist/components/wf-lorem.js";
import { WfP as WfPElement, defineCustomElement as defineWfP } from "wireframes/dist/components/wf-p.js";
import { WfTabContent as WfTabContentElement, defineCustomElement as defineWfTabContent } from "wireframes/dist/components/wf-tab-content.js";
import { WfTabHeader as WfTabHeaderElement, defineCustomElement as defineWfTabHeader } from "wireframes/dist/components/wf-tab-header.js";
import { WfTabs as WfTabsElement, defineCustomElement as defineWfTabs } from "wireframes/dist/components/wf-tabs.js";
import { WfTitle as WfTitleElement, defineCustomElement as defineWfTitle } from "wireframes/dist/components/wf-title.js";
import { WfVideo as WfVideoElement, defineCustomElement as defineWfVideo } from "wireframes/dist/components/wf-video.js";

type WfButtonEvents = NonNullable<unknown>;

export const WfButton: StencilReactComponent<WfButtonElement, WfButtonEvents> = /*@__PURE__*/ createComponent<WfButtonElement, WfButtonEvents>({
    tagName: 'wf-button',
    elementClass: WfButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as WfButtonEvents,
    defineCustomElement: defineWfButton
});

type WfCheckboxEvents = NonNullable<unknown>;

export const WfCheckbox: StencilReactComponent<WfCheckboxElement, WfCheckboxEvents> = /*@__PURE__*/ createComponent<WfCheckboxElement, WfCheckboxEvents>({
    tagName: 'wf-checkbox',
    elementClass: WfCheckboxElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as WfCheckboxEvents,
    defineCustomElement: defineWfCheckbox
});

type WfFlexEvents = NonNullable<unknown>;

export const WfFlex: StencilReactComponent<WfFlexElement, WfFlexEvents> = /*@__PURE__*/ createComponent<WfFlexElement, WfFlexEvents>({
    tagName: 'wf-flex',
    elementClass: WfFlexElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as WfFlexEvents,
    defineCustomElement: defineWfFlex
});

type WfGridEvents = NonNullable<unknown>;

export const WfGrid: StencilReactComponent<WfGridElement, WfGridEvents> = /*@__PURE__*/ createComponent<WfGridElement, WfGridEvents>({
    tagName: 'wf-grid',
    elementClass: WfGridElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as WfGridEvents,
    defineCustomElement: defineWfGrid
});

type WfHrEvents = NonNullable<unknown>;

export const WfHr: StencilReactComponent<WfHrElement, WfHrEvents> = /*@__PURE__*/ createComponent<WfHrElement, WfHrEvents>({
    tagName: 'wf-hr',
    elementClass: WfHrElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as WfHrEvents,
    defineCustomElement: defineWfHr
});

type WfImageEvents = NonNullable<unknown>;

export const WfImage: StencilReactComponent<WfImageElement, WfImageEvents> = /*@__PURE__*/ createComponent<WfImageElement, WfImageEvents>({
    tagName: 'wf-image',
    elementClass: WfImageElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as WfImageEvents,
    defineCustomElement: defineWfImage
});

type WfInputEvents = NonNullable<unknown>;

export const WfInput: StencilReactComponent<WfInputElement, WfInputEvents> = /*@__PURE__*/ createComponent<WfInputElement, WfInputEvents>({
    tagName: 'wf-input',
    elementClass: WfInputElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as WfInputEvents,
    defineCustomElement: defineWfInput
});

type WfLinkEvents = NonNullable<unknown>;

export const WfLink: StencilReactComponent<WfLinkElement, WfLinkEvents> = /*@__PURE__*/ createComponent<WfLinkElement, WfLinkEvents>({
    tagName: 'wf-link',
    elementClass: WfLinkElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as WfLinkEvents,
    defineCustomElement: defineWfLink
});

type WfLoremEvents = NonNullable<unknown>;

export const WfLorem: StencilReactComponent<WfLoremElement, WfLoremEvents> = /*@__PURE__*/ createComponent<WfLoremElement, WfLoremEvents>({
    tagName: 'wf-lorem',
    elementClass: WfLoremElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as WfLoremEvents,
    defineCustomElement: defineWfLorem
});

type WfPEvents = NonNullable<unknown>;

export const WfP: StencilReactComponent<WfPElement, WfPEvents> = /*@__PURE__*/ createComponent<WfPElement, WfPEvents>({
    tagName: 'wf-p',
    elementClass: WfPElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as WfPEvents,
    defineCustomElement: defineWfP
});

type WfTabContentEvents = NonNullable<unknown>;

export const WfTabContent: StencilReactComponent<WfTabContentElement, WfTabContentEvents> = /*@__PURE__*/ createComponent<WfTabContentElement, WfTabContentEvents>({
    tagName: 'wf-tab-content',
    elementClass: WfTabContentElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as WfTabContentEvents,
    defineCustomElement: defineWfTabContent
});

type WfTabHeaderEvents = { onSelected: EventName<CustomEvent<any>> };

export const WfTabHeader: StencilReactComponent<WfTabHeaderElement, WfTabHeaderEvents> = /*@__PURE__*/ createComponent<WfTabHeaderElement, WfTabHeaderEvents>({
    tagName: 'wf-tab-header',
    elementClass: WfTabHeaderElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onSelected: 'selected' } as WfTabHeaderEvents,
    defineCustomElement: defineWfTabHeader
});

type WfTabsEvents = NonNullable<unknown>;

export const WfTabs: StencilReactComponent<WfTabsElement, WfTabsEvents> = /*@__PURE__*/ createComponent<WfTabsElement, WfTabsEvents>({
    tagName: 'wf-tabs',
    elementClass: WfTabsElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as WfTabsEvents,
    defineCustomElement: defineWfTabs
});

type WfTitleEvents = NonNullable<unknown>;

export const WfTitle: StencilReactComponent<WfTitleElement, WfTitleEvents> = /*@__PURE__*/ createComponent<WfTitleElement, WfTitleEvents>({
    tagName: 'wf-title',
    elementClass: WfTitleElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as WfTitleEvents,
    defineCustomElement: defineWfTitle
});

type WfVideoEvents = NonNullable<unknown>;

export const WfVideo: StencilReactComponent<WfVideoElement, WfVideoEvents> = /*@__PURE__*/ createComponent<WfVideoElement, WfVideoEvents>({
    tagName: 'wf-video',
    elementClass: WfVideoElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as WfVideoEvents,
    defineCustomElement: defineWfVideo
});
