import { defineWfButton } from './wf-button.js';
import { defineWfCheckbox } from './wf-checkbox.js';
import { defineWfContainer } from './wf-container.js';
import { defineWfFlex } from './wf-flex.js';
import { defineWfGrid } from './wf-grid.js';
import { defineWfHr } from './wf-hr.js';
import { defineWfImage } from './wf-image.js';
import { defineWfInput } from './wf-input.js';
import { defineWfLink } from './wf-link.js';
import { defineWfLorem } from './wf-lorem.js';
import { defineWfP } from './wf-p.js';
import { defineWfTabs } from './wf-tabs.js';
import { defineWfTitle } from './wf-title.js';
import { defineWfVideo } from './wf-video.js';
import { defineWfBadge } from './wf-badge.js';
import { defineWfProgress } from './wf-progress.js';
import { defineWfRadioGroup } from './wf-radio-group.js';
import { defineWfRadio } from './wf-radio.js';
import { defineWfSelect } from './wf-select.js';
import { defineWfSlider } from './wf-slider.js';
import { defineWfTable } from './wf-table.js';
import { defineWfTextarea } from './wf-textarea.js';

export { WfButton, defineWfButton } from './wf-button.js';
export { WfCheckbox, defineWfCheckbox } from './wf-checkbox.js';
export { WfContainer, defineWfContainer } from './wf-container.js';
export { WfFlex, defineWfFlex } from './wf-flex.js';
export { WfGrid, defineWfGrid } from './wf-grid.js';
export { WfHr, defineWfHr } from './wf-hr.js';
export { WfImage, defineWfImage } from './wf-image.js';
export { WfInput, defineWfInput } from './wf-input.js';
export { WfLink, defineWfLink } from './wf-link.js';
export { WfLorem, defineWfLorem } from './wf-lorem.js';
export { WfP, defineWfP } from './wf-p.js';
export { WfTabs, WfTabHeader, WfTabContent, defineWfTabs } from './wf-tabs.js';
export { WfTitle, defineWfTitle } from './wf-title.js';
export { WfVideo, defineWfVideo } from './wf-video.js';
export { WfBadge, defineWfBadge } from './wf-badge.js';
export { WfProgress, defineWfProgress } from './wf-progress.js';
export { WfRadioGroup, defineWfRadioGroup } from './wf-radio-group.js';
export { WfRadio, defineWfRadio } from './wf-radio.js';
export { WfSelect, defineWfSelect } from './wf-select.js';
export { WfSlider, defineWfSlider } from './wf-slider.js';
export { WfTable, defineWfTable } from './wf-table.js';
export { WfTextarea, defineWfTextarea } from './wf-textarea.js';

export function defineCustomElements() {
  defineWfTabs();
  defineWfButton();
  defineWfCheckbox();
  defineWfContainer();
  defineWfFlex();
  defineWfGrid();
  defineWfHr();
  defineWfImage();
  defineWfInput();
  defineWfLink();
  defineWfLorem();
  defineWfP();
  defineWfTitle();
  defineWfVideo();
  defineWfBadge();
  defineWfProgress();
  defineWfRadioGroup();
  defineWfRadio();
  defineWfSelect();
  defineWfSlider();
  defineWfTable();
  defineWfTextarea();
}

defineCustomElements();
