/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WfButton {
        "backgroundColor"?: string;
        "borderColor"?: string;
        "color"?: string;
        "variant"?: 'sm' | 'md' | 'lg' | 'xl';
    }
    interface WfCheckbox {
    }
    interface WfContainer {
        "padding"?: string;
        "width"?: string;
    }
    interface WfFlex {
        "alignItems"?: 'flex-start' | 'center' | 'flex-end' | 'stretch' | 'baseline';
        "flexDirection"?: string;
        "flexWrap"?: 'wrap' | 'nowrap' | 'wrap-reverse';
        "gap"?: string;
        "height"?: string;
        "justifyContent"?: 'flex-start' | 'center' | 'flex-end' | 'space-between' | 'space-around' | 'space-evenly';
        "margin"?: string;
    }
    interface WfGrid {
        "alignItems"?: 'flex-start' | 'center' | 'flex-end' | 'stretch' | 'baseline';
        "gap"?: string;
        "justifyContent"?: 'flex-start' | 'center' | 'flex-end' | 'space-between' | 'space-around' | 'space-evenly';
        "justifyItems"?: 'flex-start' | 'center' | 'flex-end' | 'space-between' | 'space-around' | 'space-evenly';
    }
    interface WfHr {
        "width"?: string;
    }
    interface WfImage {
        "aspectRatio"?: string;
        "borderRadius"?: string;
        "height"?: string;
        "text"?: string;
        "width"?: string;
    }
    interface WfInput {
        "maxWidth"?: string;
        "placeholder": string;
        "variant"?: 'sm' | 'md' | 'lg' | 'xl';
        "width"?: string;
    }
    interface WfLink {
        "href"?: string;
        "target"?: string;
    }
    interface WfLorem {
        /**
          * @default 2
         */
        "words"?: number;
    }
    interface WfP {
        /**
          * Size of the font
         */
        "fontSize"?: string;
        /**
          * Text align
         */
        "textAlign"?: 'left' | 'center' | 'right' | 'justify';
    }
    interface WfTabContent {
        "getChild": () => Promise<{ select: any; unselect: any; name: string; }>;
        "name"?: string;
    }
    interface WfTabHeader {
        "getChild": () => Promise<{ select: any; unselect: any; name: string; }>;
        "name"?: string;
    }
    interface WfTabs {
        "names"?: string;
    }
    interface WfTitle {
        "fontWeight"?: string;
        /**
          * @default 'h1'
         */
        "tag"?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
        "textAlign"?: string;
        "variant"?: 'sm' | 'md' | 'lg' | 'xl';
    }
    interface WfVideo {
        /**
          * @default '16 / 9'
         */
        "aspectRatio"?: string;
        "height"?: string;
        "margin"?: string;
        "maxWidth"?: string;
        "width"?: string;
    }
}
export interface WfTabHeaderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWfTabHeaderElement;
}
declare global {
    interface HTMLWfButtonElement extends Components.WfButton, HTMLStencilElement {
    }
    var HTMLWfButtonElement: {
        prototype: HTMLWfButtonElement;
        new (): HTMLWfButtonElement;
    };
    interface HTMLWfCheckboxElement extends Components.WfCheckbox, HTMLStencilElement {
    }
    var HTMLWfCheckboxElement: {
        prototype: HTMLWfCheckboxElement;
        new (): HTMLWfCheckboxElement;
    };
    interface HTMLWfContainerElement extends Components.WfContainer, HTMLStencilElement {
    }
    var HTMLWfContainerElement: {
        prototype: HTMLWfContainerElement;
        new (): HTMLWfContainerElement;
    };
    interface HTMLWfFlexElement extends Components.WfFlex, HTMLStencilElement {
    }
    var HTMLWfFlexElement: {
        prototype: HTMLWfFlexElement;
        new (): HTMLWfFlexElement;
    };
    interface HTMLWfGridElement extends Components.WfGrid, HTMLStencilElement {
    }
    var HTMLWfGridElement: {
        prototype: HTMLWfGridElement;
        new (): HTMLWfGridElement;
    };
    interface HTMLWfHrElement extends Components.WfHr, HTMLStencilElement {
    }
    var HTMLWfHrElement: {
        prototype: HTMLWfHrElement;
        new (): HTMLWfHrElement;
    };
    interface HTMLWfImageElement extends Components.WfImage, HTMLStencilElement {
    }
    var HTMLWfImageElement: {
        prototype: HTMLWfImageElement;
        new (): HTMLWfImageElement;
    };
    interface HTMLWfInputElement extends Components.WfInput, HTMLStencilElement {
    }
    var HTMLWfInputElement: {
        prototype: HTMLWfInputElement;
        new (): HTMLWfInputElement;
    };
    interface HTMLWfLinkElement extends Components.WfLink, HTMLStencilElement {
    }
    var HTMLWfLinkElement: {
        prototype: HTMLWfLinkElement;
        new (): HTMLWfLinkElement;
    };
    interface HTMLWfLoremElement extends Components.WfLorem, HTMLStencilElement {
    }
    var HTMLWfLoremElement: {
        prototype: HTMLWfLoremElement;
        new (): HTMLWfLoremElement;
    };
    interface HTMLWfPElement extends Components.WfP, HTMLStencilElement {
    }
    var HTMLWfPElement: {
        prototype: HTMLWfPElement;
        new (): HTMLWfPElement;
    };
    interface HTMLWfTabContentElement extends Components.WfTabContent, HTMLStencilElement {
    }
    var HTMLWfTabContentElement: {
        prototype: HTMLWfTabContentElement;
        new (): HTMLWfTabContentElement;
    };
    interface HTMLWfTabHeaderElementEventMap {
        "selected": any;
    }
    interface HTMLWfTabHeaderElement extends Components.WfTabHeader, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWfTabHeaderElementEventMap>(type: K, listener: (this: HTMLWfTabHeaderElement, ev: WfTabHeaderCustomEvent<HTMLWfTabHeaderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWfTabHeaderElementEventMap>(type: K, listener: (this: HTMLWfTabHeaderElement, ev: WfTabHeaderCustomEvent<HTMLWfTabHeaderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWfTabHeaderElement: {
        prototype: HTMLWfTabHeaderElement;
        new (): HTMLWfTabHeaderElement;
    };
    interface HTMLWfTabsElement extends Components.WfTabs, HTMLStencilElement {
    }
    var HTMLWfTabsElement: {
        prototype: HTMLWfTabsElement;
        new (): HTMLWfTabsElement;
    };
    interface HTMLWfTitleElement extends Components.WfTitle, HTMLStencilElement {
    }
    var HTMLWfTitleElement: {
        prototype: HTMLWfTitleElement;
        new (): HTMLWfTitleElement;
    };
    interface HTMLWfVideoElement extends Components.WfVideo, HTMLStencilElement {
    }
    var HTMLWfVideoElement: {
        prototype: HTMLWfVideoElement;
        new (): HTMLWfVideoElement;
    };
    interface HTMLElementTagNameMap {
        "wf-button": HTMLWfButtonElement;
        "wf-checkbox": HTMLWfCheckboxElement;
        "wf-container": HTMLWfContainerElement;
        "wf-flex": HTMLWfFlexElement;
        "wf-grid": HTMLWfGridElement;
        "wf-hr": HTMLWfHrElement;
        "wf-image": HTMLWfImageElement;
        "wf-input": HTMLWfInputElement;
        "wf-link": HTMLWfLinkElement;
        "wf-lorem": HTMLWfLoremElement;
        "wf-p": HTMLWfPElement;
        "wf-tab-content": HTMLWfTabContentElement;
        "wf-tab-header": HTMLWfTabHeaderElement;
        "wf-tabs": HTMLWfTabsElement;
        "wf-title": HTMLWfTitleElement;
        "wf-video": HTMLWfVideoElement;
    }
}
declare namespace LocalJSX {
    interface WfButton {
        "backgroundColor"?: string;
        "borderColor"?: string;
        "color"?: string;
        "variant"?: 'sm' | 'md' | 'lg' | 'xl';
    }
    interface WfCheckbox {
    }
    interface WfContainer {
        "padding"?: string;
        "width"?: string;
    }
    interface WfFlex {
        "alignItems"?: 'flex-start' | 'center' | 'flex-end' | 'stretch' | 'baseline';
        "flexDirection"?: string;
        "flexWrap"?: 'wrap' | 'nowrap' | 'wrap-reverse';
        "gap"?: string;
        "height"?: string;
        "justifyContent"?: 'flex-start' | 'center' | 'flex-end' | 'space-between' | 'space-around' | 'space-evenly';
        "margin"?: string;
    }
    interface WfGrid {
        "alignItems"?: 'flex-start' | 'center' | 'flex-end' | 'stretch' | 'baseline';
        "gap"?: string;
        "justifyContent"?: 'flex-start' | 'center' | 'flex-end' | 'space-between' | 'space-around' | 'space-evenly';
        "justifyItems"?: 'flex-start' | 'center' | 'flex-end' | 'space-between' | 'space-around' | 'space-evenly';
    }
    interface WfHr {
        "width"?: string;
    }
    interface WfImage {
        "aspectRatio"?: string;
        "borderRadius"?: string;
        "height"?: string;
        "text"?: string;
        "width"?: string;
    }
    interface WfInput {
        "maxWidth"?: string;
        "placeholder"?: string;
        "variant"?: 'sm' | 'md' | 'lg' | 'xl';
        "width"?: string;
    }
    interface WfLink {
        "href"?: string;
        "target"?: string;
    }
    interface WfLorem {
        /**
          * @default 2
         */
        "words"?: number;
    }
    interface WfP {
        /**
          * Size of the font
         */
        "fontSize"?: string;
        /**
          * Text align
         */
        "textAlign"?: 'left' | 'center' | 'right' | 'justify';
    }
    interface WfTabContent {
        "name"?: string;
    }
    interface WfTabHeader {
        "name"?: string;
        "onSelected"?: (event: WfTabHeaderCustomEvent<any>) => void;
    }
    interface WfTabs {
        "names"?: string;
    }
    interface WfTitle {
        "fontWeight"?: string;
        /**
          * @default 'h1'
         */
        "tag"?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
        "textAlign"?: string;
        "variant"?: 'sm' | 'md' | 'lg' | 'xl';
    }
    interface WfVideo {
        /**
          * @default '16 / 9'
         */
        "aspectRatio"?: string;
        "height"?: string;
        "margin"?: string;
        "maxWidth"?: string;
        "width"?: string;
    }

    interface WfButtonAttributes {
        "backgroundColor": string;
        "color": string;
        "borderColor": string;
        "variant": 'sm' | 'md' | 'lg' | 'xl';
    }
    interface WfContainerAttributes {
        "width": string;
        "padding": string;
    }
    interface WfFlexAttributes {
        "alignItems": 'flex-start' | 'center' | 'flex-end' | 'stretch' | 'baseline';
        "justifyContent": 'flex-start' | 'center' | 'flex-end' | 'space-between' | 'space-around' | 'space-evenly';
        "gap": string;
        "margin": string;
        "height": string;
        "flexDirection": string;
        "flexWrap": 'wrap' | 'nowrap' | 'wrap-reverse';
    }
    interface WfGridAttributes {
        "alignItems": 'flex-start' | 'center' | 'flex-end' | 'stretch' | 'baseline';
        "justifyContent": 'flex-start' | 'center' | 'flex-end' | 'space-between' | 'space-around' | 'space-evenly';
        "justifyItems": 'flex-start' | 'center' | 'flex-end' | 'space-between' | 'space-around' | 'space-evenly';
        "gap": string;
    }
    interface WfHrAttributes {
        "width": string;
    }
    interface WfImageAttributes {
        "width": string;
        "height": string;
        "aspectRatio": string;
        "text": string;
        "borderRadius": string;
    }
    interface WfInputAttributes {
        "width": string;
        "maxWidth": string;
        "placeholder": string;
        "variant": 'sm' | 'md' | 'lg' | 'xl';
    }
    interface WfLinkAttributes {
        "href": string;
        "target": string;
    }
    interface WfLoremAttributes {
        "words": number;
    }
    interface WfPAttributes {
        "fontSize": string;
        "textAlign": 'left' | 'center' | 'right' | 'justify';
    }
    interface WfTabContentAttributes {
        "name": string;
    }
    interface WfTabHeaderAttributes {
        "name": string;
    }
    interface WfTabsAttributes {
        "names": string;
    }
    interface WfTitleAttributes {
        "tag": 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
        "fontWeight": string;
        "textAlign": string;
        "variant": 'sm' | 'md' | 'lg' | 'xl';
    }
    interface WfVideoAttributes {
        "width": string;
        "maxWidth": string;
        "height": string;
        "aspectRatio": string;
        "margin": string;
    }

    interface IntrinsicElements {
        "wf-button": Omit<WfButton, keyof WfButtonAttributes> & { [K in keyof WfButton & keyof WfButtonAttributes]?: WfButton[K] } & { [K in keyof WfButton & keyof WfButtonAttributes as `attr:${K}`]?: WfButtonAttributes[K] } & { [K in keyof WfButton & keyof WfButtonAttributes as `prop:${K}`]?: WfButton[K] };
        "wf-checkbox": WfCheckbox;
        "wf-container": Omit<WfContainer, keyof WfContainerAttributes> & { [K in keyof WfContainer & keyof WfContainerAttributes]?: WfContainer[K] } & { [K in keyof WfContainer & keyof WfContainerAttributes as `attr:${K}`]?: WfContainerAttributes[K] } & { [K in keyof WfContainer & keyof WfContainerAttributes as `prop:${K}`]?: WfContainer[K] };
        "wf-flex": Omit<WfFlex, keyof WfFlexAttributes> & { [K in keyof WfFlex & keyof WfFlexAttributes]?: WfFlex[K] } & { [K in keyof WfFlex & keyof WfFlexAttributes as `attr:${K}`]?: WfFlexAttributes[K] } & { [K in keyof WfFlex & keyof WfFlexAttributes as `prop:${K}`]?: WfFlex[K] };
        "wf-grid": Omit<WfGrid, keyof WfGridAttributes> & { [K in keyof WfGrid & keyof WfGridAttributes]?: WfGrid[K] } & { [K in keyof WfGrid & keyof WfGridAttributes as `attr:${K}`]?: WfGridAttributes[K] } & { [K in keyof WfGrid & keyof WfGridAttributes as `prop:${K}`]?: WfGrid[K] };
        "wf-hr": Omit<WfHr, keyof WfHrAttributes> & { [K in keyof WfHr & keyof WfHrAttributes]?: WfHr[K] } & { [K in keyof WfHr & keyof WfHrAttributes as `attr:${K}`]?: WfHrAttributes[K] } & { [K in keyof WfHr & keyof WfHrAttributes as `prop:${K}`]?: WfHr[K] };
        "wf-image": Omit<WfImage, keyof WfImageAttributes> & { [K in keyof WfImage & keyof WfImageAttributes]?: WfImage[K] } & { [K in keyof WfImage & keyof WfImageAttributes as `attr:${K}`]?: WfImageAttributes[K] } & { [K in keyof WfImage & keyof WfImageAttributes as `prop:${K}`]?: WfImage[K] };
        "wf-input": Omit<WfInput, keyof WfInputAttributes> & { [K in keyof WfInput & keyof WfInputAttributes]?: WfInput[K] } & { [K in keyof WfInput & keyof WfInputAttributes as `attr:${K}`]?: WfInputAttributes[K] } & { [K in keyof WfInput & keyof WfInputAttributes as `prop:${K}`]?: WfInput[K] };
        "wf-link": Omit<WfLink, keyof WfLinkAttributes> & { [K in keyof WfLink & keyof WfLinkAttributes]?: WfLink[K] } & { [K in keyof WfLink & keyof WfLinkAttributes as `attr:${K}`]?: WfLinkAttributes[K] } & { [K in keyof WfLink & keyof WfLinkAttributes as `prop:${K}`]?: WfLink[K] };
        "wf-lorem": Omit<WfLorem, keyof WfLoremAttributes> & { [K in keyof WfLorem & keyof WfLoremAttributes]?: WfLorem[K] } & { [K in keyof WfLorem & keyof WfLoremAttributes as `attr:${K}`]?: WfLoremAttributes[K] } & { [K in keyof WfLorem & keyof WfLoremAttributes as `prop:${K}`]?: WfLorem[K] };
        "wf-p": Omit<WfP, keyof WfPAttributes> & { [K in keyof WfP & keyof WfPAttributes]?: WfP[K] } & { [K in keyof WfP & keyof WfPAttributes as `attr:${K}`]?: WfPAttributes[K] } & { [K in keyof WfP & keyof WfPAttributes as `prop:${K}`]?: WfP[K] };
        "wf-tab-content": Omit<WfTabContent, keyof WfTabContentAttributes> & { [K in keyof WfTabContent & keyof WfTabContentAttributes]?: WfTabContent[K] } & { [K in keyof WfTabContent & keyof WfTabContentAttributes as `attr:${K}`]?: WfTabContentAttributes[K] } & { [K in keyof WfTabContent & keyof WfTabContentAttributes as `prop:${K}`]?: WfTabContent[K] };
        "wf-tab-header": Omit<WfTabHeader, keyof WfTabHeaderAttributes> & { [K in keyof WfTabHeader & keyof WfTabHeaderAttributes]?: WfTabHeader[K] } & { [K in keyof WfTabHeader & keyof WfTabHeaderAttributes as `attr:${K}`]?: WfTabHeaderAttributes[K] } & { [K in keyof WfTabHeader & keyof WfTabHeaderAttributes as `prop:${K}`]?: WfTabHeader[K] };
        "wf-tabs": Omit<WfTabs, keyof WfTabsAttributes> & { [K in keyof WfTabs & keyof WfTabsAttributes]?: WfTabs[K] } & { [K in keyof WfTabs & keyof WfTabsAttributes as `attr:${K}`]?: WfTabsAttributes[K] } & { [K in keyof WfTabs & keyof WfTabsAttributes as `prop:${K}`]?: WfTabs[K] };
        "wf-title": Omit<WfTitle, keyof WfTitleAttributes> & { [K in keyof WfTitle & keyof WfTitleAttributes]?: WfTitle[K] } & { [K in keyof WfTitle & keyof WfTitleAttributes as `attr:${K}`]?: WfTitleAttributes[K] } & { [K in keyof WfTitle & keyof WfTitleAttributes as `prop:${K}`]?: WfTitle[K] };
        "wf-video": Omit<WfVideo, keyof WfVideoAttributes> & { [K in keyof WfVideo & keyof WfVideoAttributes]?: WfVideo[K] } & { [K in keyof WfVideo & keyof WfVideoAttributes as `attr:${K}`]?: WfVideoAttributes[K] } & { [K in keyof WfVideo & keyof WfVideoAttributes as `prop:${K}`]?: WfVideo[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wf-button": LocalJSX.IntrinsicElements["wf-button"] & JSXBase.HTMLAttributes<HTMLWfButtonElement>;
            "wf-checkbox": LocalJSX.IntrinsicElements["wf-checkbox"] & JSXBase.HTMLAttributes<HTMLWfCheckboxElement>;
            "wf-container": LocalJSX.IntrinsicElements["wf-container"] & JSXBase.HTMLAttributes<HTMLWfContainerElement>;
            "wf-flex": LocalJSX.IntrinsicElements["wf-flex"] & JSXBase.HTMLAttributes<HTMLWfFlexElement>;
            "wf-grid": LocalJSX.IntrinsicElements["wf-grid"] & JSXBase.HTMLAttributes<HTMLWfGridElement>;
            "wf-hr": LocalJSX.IntrinsicElements["wf-hr"] & JSXBase.HTMLAttributes<HTMLWfHrElement>;
            "wf-image": LocalJSX.IntrinsicElements["wf-image"] & JSXBase.HTMLAttributes<HTMLWfImageElement>;
            "wf-input": LocalJSX.IntrinsicElements["wf-input"] & JSXBase.HTMLAttributes<HTMLWfInputElement>;
            "wf-link": LocalJSX.IntrinsicElements["wf-link"] & JSXBase.HTMLAttributes<HTMLWfLinkElement>;
            "wf-lorem": LocalJSX.IntrinsicElements["wf-lorem"] & JSXBase.HTMLAttributes<HTMLWfLoremElement>;
            "wf-p": LocalJSX.IntrinsicElements["wf-p"] & JSXBase.HTMLAttributes<HTMLWfPElement>;
            "wf-tab-content": LocalJSX.IntrinsicElements["wf-tab-content"] & JSXBase.HTMLAttributes<HTMLWfTabContentElement>;
            "wf-tab-header": LocalJSX.IntrinsicElements["wf-tab-header"] & JSXBase.HTMLAttributes<HTMLWfTabHeaderElement>;
            "wf-tabs": LocalJSX.IntrinsicElements["wf-tabs"] & JSXBase.HTMLAttributes<HTMLWfTabsElement>;
            "wf-title": LocalJSX.IntrinsicElements["wf-title"] & JSXBase.HTMLAttributes<HTMLWfTitleElement>;
            "wf-video": LocalJSX.IntrinsicElements["wf-video"] & JSXBase.HTMLAttributes<HTMLWfVideoElement>;
        }
    }
}
